// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlg-byOzAklQijR972uvILosto5lQ-BnM',
    appId: '1:222519781384:web:a96614d467e04cce1d89bd',
    messagingSenderId: '222519781384',
    projectId: 'udemycoursefirebase-fe71d',
    authDomain: 'udemycoursefirebase-fe71d.firebaseapp.com',
    storageBucket: 'udemycoursefirebase-fe71d.appspot.com',
    measurementId: 'G-L9BQBR29B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUg7d1d-zkO8RT-Paz2zqRKmN1PXs_7mU',
    appId: '1:222519781384:android:ecfa67732b3130211d89bd',
    messagingSenderId: '222519781384',
    projectId: 'udemycoursefirebase-fe71d',
    storageBucket: 'udemycoursefirebase-fe71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUNLmQzaKy6nI-Es3L_1AOILFJqltJoE',
    appId: '1:222519781384:ios:658ff93319b1f9db1d89bd',
    messagingSenderId: '222519781384',
    projectId: 'udemycoursefirebase-fe71d',
    storageBucket: 'udemycoursefirebase-fe71d.appspot.com',
    iosBundleId: 'com.bassel.socialFirebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDUNLmQzaKy6nI-Es3L_1AOILFJqltJoE',
    appId: '1:222519781384:ios:be88b0ea6b6d86971d89bd',
    messagingSenderId: '222519781384',
    projectId: 'udemycoursefirebase-fe71d',
    storageBucket: 'udemycoursefirebase-fe71d.appspot.com',
    iosBundleId: 'com.example.socialFirebaseCourse.RunnerTests',
  );
}
